package com.sc.domain;

public class RadCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_RADCODE.CM_USERID
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    private String cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_RADCODE.CM_CODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    private Integer cmCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_RADCODE.CM_USERID
     *
     * @return the value of TB_RADCODE.CM_USERID
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    public String getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_RADCODE.CM_USERID
     *
     * @param cmUserid the value for TB_RADCODE.CM_USERID
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    public void setCmUserid(String cmUserid) {
        this.cmUserid = cmUserid == null ? null : cmUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_RADCODE.CM_CODE
     *
     * @return the value of TB_RADCODE.CM_CODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    public Integer getCmCode() {
        return cmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_RADCODE.CM_CODE
     *
     * @param cmCode the value for TB_RADCODE.CM_CODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    public void setCmCode(Integer cmCode) {
        this.cmCode = cmCode;
    }
}