package com.sc.domain;

public class Register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REGISTER.CM_PHONE
     *
     * @mbg.generated Sat Apr 15 08:26:44 CST 2017
     */
    private Long cmPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REGISTER.CM_CODE
     *
     * @mbg.generated Sat Apr 15 08:26:44 CST 2017
     */
    private Integer cmCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REGISTER.CM_PHONE
     *
     * @return the value of TB_REGISTER.CM_PHONE
     *
     * @mbg.generated Sat Apr 15 08:26:44 CST 2017
     */
    public Long getCmPhone() {
        return cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REGISTER.CM_PHONE
     *
     * @param cmPhone the value for TB_REGISTER.CM_PHONE
     *
     * @mbg.generated Sat Apr 15 08:26:44 CST 2017
     */
    public void setCmPhone(Long cmPhone) {
        this.cmPhone = cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REGISTER.CM_CODE
     *
     * @return the value of TB_REGISTER.CM_CODE
     *
     * @mbg.generated Sat Apr 15 08:26:44 CST 2017
     */
    public Integer getCmCode() {
        return cmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REGISTER.CM_CODE
     *
     * @param cmCode the value for TB_REGISTER.CM_CODE
     *
     * @mbg.generated Sat Apr 15 08:26:44 CST 2017
     */
    public void setCmCode(Integer cmCode) {
        this.cmCode = cmCode;
    }
}