package com.sc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCmUseridIsNull() {
            addCriterion("CM_USERID is null");
            return (Criteria) this;
        }

        public Criteria andCmUseridIsNotNull() {
            addCriterion("CM_USERID is not null");
            return (Criteria) this;
        }

        public Criteria andCmUseridEqualTo(String value) {
            addCriterion("CM_USERID =", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridNotEqualTo(String value) {
            addCriterion("CM_USERID <>", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridGreaterThan(String value) {
            addCriterion("CM_USERID >", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridGreaterThanOrEqualTo(String value) {
            addCriterion("CM_USERID >=", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridLessThan(String value) {
            addCriterion("CM_USERID <", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridLessThanOrEqualTo(String value) {
            addCriterion("CM_USERID <=", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridLike(String value) {
            addCriterion("CM_USERID like", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridNotLike(String value) {
            addCriterion("CM_USERID not like", value, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridIn(List<String> values) {
            addCriterion("CM_USERID in", values, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridNotIn(List<String> values) {
            addCriterion("CM_USERID not in", values, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridBetween(String value1, String value2) {
            addCriterion("CM_USERID between", value1, value2, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmUseridNotBetween(String value1, String value2) {
            addCriterion("CM_USERID not between", value1, value2, "cmUserid");
            return (Criteria) this;
        }

        public Criteria andCmNicknameIsNull() {
            addCriterion("CM_NICKNAME is null");
            return (Criteria) this;
        }

        public Criteria andCmNicknameIsNotNull() {
            addCriterion("CM_NICKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCmNicknameEqualTo(String value) {
            addCriterion("CM_NICKNAME =", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameNotEqualTo(String value) {
            addCriterion("CM_NICKNAME <>", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameGreaterThan(String value) {
            addCriterion("CM_NICKNAME >", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("CM_NICKNAME >=", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameLessThan(String value) {
            addCriterion("CM_NICKNAME <", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameLessThanOrEqualTo(String value) {
            addCriterion("CM_NICKNAME <=", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameLike(String value) {
            addCriterion("CM_NICKNAME like", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameNotLike(String value) {
            addCriterion("CM_NICKNAME not like", value, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameIn(List<String> values) {
            addCriterion("CM_NICKNAME in", values, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameNotIn(List<String> values) {
            addCriterion("CM_NICKNAME not in", values, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameBetween(String value1, String value2) {
            addCriterion("CM_NICKNAME between", value1, value2, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmNicknameNotBetween(String value1, String value2) {
            addCriterion("CM_NICKNAME not between", value1, value2, "cmNickname");
            return (Criteria) this;
        }

        public Criteria andCmPhoneIsNull() {
            addCriterion("CM_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andCmPhoneIsNotNull() {
            addCriterion("CM_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andCmPhoneEqualTo(Long value) {
            addCriterion("CM_PHONE =", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneNotEqualTo(Long value) {
            addCriterion("CM_PHONE <>", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneGreaterThan(Long value) {
            addCriterion("CM_PHONE >", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneGreaterThanOrEqualTo(Long value) {
            addCriterion("CM_PHONE >=", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneLessThan(Long value) {
            addCriterion("CM_PHONE <", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneLessThanOrEqualTo(Long value) {
            addCriterion("CM_PHONE <=", value, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneIn(List<Long> values) {
            addCriterion("CM_PHONE in", values, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneNotIn(List<Long> values) {
            addCriterion("CM_PHONE not in", values, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneBetween(Long value1, Long value2) {
            addCriterion("CM_PHONE between", value1, value2, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmPhoneNotBetween(Long value1, Long value2) {
            addCriterion("CM_PHONE not between", value1, value2, "cmPhone");
            return (Criteria) this;
        }

        public Criteria andCmAccountIsNull() {
            addCriterion("CM_ACCOUNT is null");
            return (Criteria) this;
        }

        public Criteria andCmAccountIsNotNull() {
            addCriterion("CM_ACCOUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCmAccountEqualTo(String value) {
            addCriterion("CM_ACCOUNT =", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountNotEqualTo(String value) {
            addCriterion("CM_ACCOUNT <>", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountGreaterThan(String value) {
            addCriterion("CM_ACCOUNT >", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountGreaterThanOrEqualTo(String value) {
            addCriterion("CM_ACCOUNT >=", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountLessThan(String value) {
            addCriterion("CM_ACCOUNT <", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountLessThanOrEqualTo(String value) {
            addCriterion("CM_ACCOUNT <=", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountLike(String value) {
            addCriterion("CM_ACCOUNT like", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountNotLike(String value) {
            addCriterion("CM_ACCOUNT not like", value, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountIn(List<String> values) {
            addCriterion("CM_ACCOUNT in", values, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountNotIn(List<String> values) {
            addCriterion("CM_ACCOUNT not in", values, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountBetween(String value1, String value2) {
            addCriterion("CM_ACCOUNT between", value1, value2, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmAccountNotBetween(String value1, String value2) {
            addCriterion("CM_ACCOUNT not between", value1, value2, "cmAccount");
            return (Criteria) this;
        }

        public Criteria andCmPasswordIsNull() {
            addCriterion("CM_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andCmPasswordIsNotNull() {
            addCriterion("CM_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andCmPasswordEqualTo(String value) {
            addCriterion("CM_PASSWORD =", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordNotEqualTo(String value) {
            addCriterion("CM_PASSWORD <>", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordGreaterThan(String value) {
            addCriterion("CM_PASSWORD >", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("CM_PASSWORD >=", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordLessThan(String value) {
            addCriterion("CM_PASSWORD <", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordLessThanOrEqualTo(String value) {
            addCriterion("CM_PASSWORD <=", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordLike(String value) {
            addCriterion("CM_PASSWORD like", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordNotLike(String value) {
            addCriterion("CM_PASSWORD not like", value, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordIn(List<String> values) {
            addCriterion("CM_PASSWORD in", values, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordNotIn(List<String> values) {
            addCriterion("CM_PASSWORD not in", values, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordBetween(String value1, String value2) {
            addCriterion("CM_PASSWORD between", value1, value2, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmPasswordNotBetween(String value1, String value2) {
            addCriterion("CM_PASSWORD not between", value1, value2, "cmPassword");
            return (Criteria) this;
        }

        public Criteria andCmIntegralIsNull() {
            addCriterion("CM_INTEGRAL is null");
            return (Criteria) this;
        }

        public Criteria andCmIntegralIsNotNull() {
            addCriterion("CM_INTEGRAL is not null");
            return (Criteria) this;
        }

        public Criteria andCmIntegralEqualTo(Integer value) {
            addCriterion("CM_INTEGRAL =", value, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralNotEqualTo(Integer value) {
            addCriterion("CM_INTEGRAL <>", value, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralGreaterThan(Integer value) {
            addCriterion("CM_INTEGRAL >", value, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("CM_INTEGRAL >=", value, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralLessThan(Integer value) {
            addCriterion("CM_INTEGRAL <", value, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("CM_INTEGRAL <=", value, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralIn(List<Integer> values) {
            addCriterion("CM_INTEGRAL in", values, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralNotIn(List<Integer> values) {
            addCriterion("CM_INTEGRAL not in", values, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralBetween(Integer value1, Integer value2) {
            addCriterion("CM_INTEGRAL between", value1, value2, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("CM_INTEGRAL not between", value1, value2, "cmIntegral");
            return (Criteria) this;
        }

        public Criteria andCmBalanceIsNull() {
            addCriterion("CM_BALANCE is null");
            return (Criteria) this;
        }

        public Criteria andCmBalanceIsNotNull() {
            addCriterion("CM_BALANCE is not null");
            return (Criteria) this;
        }

        public Criteria andCmBalanceEqualTo(Double value) {
            addCriterion("CM_BALANCE =", value, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceNotEqualTo(Double value) {
            addCriterion("CM_BALANCE <>", value, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceGreaterThan(Double value) {
            addCriterion("CM_BALANCE >", value, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceGreaterThanOrEqualTo(Double value) {
            addCriterion("CM_BALANCE >=", value, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceLessThan(Double value) {
            addCriterion("CM_BALANCE <", value, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceLessThanOrEqualTo(Double value) {
            addCriterion("CM_BALANCE <=", value, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceIn(List<Double> values) {
            addCriterion("CM_BALANCE in", values, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceNotIn(List<Double> values) {
            addCriterion("CM_BALANCE not in", values, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceBetween(Double value1, Double value2) {
            addCriterion("CM_BALANCE between", value1, value2, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmBalanceNotBetween(Double value1, Double value2) {
            addCriterion("CM_BALANCE not between", value1, value2, "cmBalance");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathIsNull() {
            addCriterion("CM_CARDFACEPATH is null");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathIsNotNull() {
            addCriterion("CM_CARDFACEPATH is not null");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathEqualTo(String value) {
            addCriterion("CM_CARDFACEPATH =", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathNotEqualTo(String value) {
            addCriterion("CM_CARDFACEPATH <>", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathGreaterThan(String value) {
            addCriterion("CM_CARDFACEPATH >", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathGreaterThanOrEqualTo(String value) {
            addCriterion("CM_CARDFACEPATH >=", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathLessThan(String value) {
            addCriterion("CM_CARDFACEPATH <", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathLessThanOrEqualTo(String value) {
            addCriterion("CM_CARDFACEPATH <=", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathLike(String value) {
            addCriterion("CM_CARDFACEPATH like", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathNotLike(String value) {
            addCriterion("CM_CARDFACEPATH not like", value, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathIn(List<String> values) {
            addCriterion("CM_CARDFACEPATH in", values, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathNotIn(List<String> values) {
            addCriterion("CM_CARDFACEPATH not in", values, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathBetween(String value1, String value2) {
            addCriterion("CM_CARDFACEPATH between", value1, value2, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardfacepathNotBetween(String value1, String value2) {
            addCriterion("CM_CARDFACEPATH not between", value1, value2, "cmCardfacepath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathIsNull() {
            addCriterion("CM_CARDBACKPATH is null");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathIsNotNull() {
            addCriterion("CM_CARDBACKPATH is not null");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathEqualTo(String value) {
            addCriterion("CM_CARDBACKPATH =", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathNotEqualTo(String value) {
            addCriterion("CM_CARDBACKPATH <>", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathGreaterThan(String value) {
            addCriterion("CM_CARDBACKPATH >", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathGreaterThanOrEqualTo(String value) {
            addCriterion("CM_CARDBACKPATH >=", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathLessThan(String value) {
            addCriterion("CM_CARDBACKPATH <", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathLessThanOrEqualTo(String value) {
            addCriterion("CM_CARDBACKPATH <=", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathLike(String value) {
            addCriterion("CM_CARDBACKPATH like", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathNotLike(String value) {
            addCriterion("CM_CARDBACKPATH not like", value, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathIn(List<String> values) {
            addCriterion("CM_CARDBACKPATH in", values, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathNotIn(List<String> values) {
            addCriterion("CM_CARDBACKPATH not in", values, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathBetween(String value1, String value2) {
            addCriterion("CM_CARDBACKPATH between", value1, value2, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmCardbackpathNotBetween(String value1, String value2) {
            addCriterion("CM_CARDBACKPATH not between", value1, value2, "cmCardbackpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathIsNull() {
            addCriterion("CM_PERSONALPATH is null");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathIsNotNull() {
            addCriterion("CM_PERSONALPATH is not null");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathEqualTo(String value) {
            addCriterion("CM_PERSONALPATH =", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathNotEqualTo(String value) {
            addCriterion("CM_PERSONALPATH <>", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathGreaterThan(String value) {
            addCriterion("CM_PERSONALPATH >", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathGreaterThanOrEqualTo(String value) {
            addCriterion("CM_PERSONALPATH >=", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathLessThan(String value) {
            addCriterion("CM_PERSONALPATH <", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathLessThanOrEqualTo(String value) {
            addCriterion("CM_PERSONALPATH <=", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathLike(String value) {
            addCriterion("CM_PERSONALPATH like", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathNotLike(String value) {
            addCriterion("CM_PERSONALPATH not like", value, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathIn(List<String> values) {
            addCriterion("CM_PERSONALPATH in", values, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathNotIn(List<String> values) {
            addCriterion("CM_PERSONALPATH not in", values, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathBetween(String value1, String value2) {
            addCriterion("CM_PERSONALPATH between", value1, value2, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmPersonalpathNotBetween(String value1, String value2) {
            addCriterion("CM_PERSONALPATH not between", value1, value2, "cmPersonalpath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathIsNull() {
            addCriterion("CM_LICENSEPATH is null");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathIsNotNull() {
            addCriterion("CM_LICENSEPATH is not null");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathEqualTo(String value) {
            addCriterion("CM_LICENSEPATH =", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathNotEqualTo(String value) {
            addCriterion("CM_LICENSEPATH <>", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathGreaterThan(String value) {
            addCriterion("CM_LICENSEPATH >", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathGreaterThanOrEqualTo(String value) {
            addCriterion("CM_LICENSEPATH >=", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathLessThan(String value) {
            addCriterion("CM_LICENSEPATH <", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathLessThanOrEqualTo(String value) {
            addCriterion("CM_LICENSEPATH <=", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathLike(String value) {
            addCriterion("CM_LICENSEPATH like", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathNotLike(String value) {
            addCriterion("CM_LICENSEPATH not like", value, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathIn(List<String> values) {
            addCriterion("CM_LICENSEPATH in", values, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathNotIn(List<String> values) {
            addCriterion("CM_LICENSEPATH not in", values, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathBetween(String value1, String value2) {
            addCriterion("CM_LICENSEPATH between", value1, value2, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmLicensepathNotBetween(String value1, String value2) {
            addCriterion("CM_LICENSEPATH not between", value1, value2, "cmLicensepath");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressIsNull() {
            addCriterion("CM_SHOPEADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressIsNotNull() {
            addCriterion("CM_SHOPEADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressEqualTo(String value) {
            addCriterion("CM_SHOPEADDRESS =", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressNotEqualTo(String value) {
            addCriterion("CM_SHOPEADDRESS <>", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressGreaterThan(String value) {
            addCriterion("CM_SHOPEADDRESS >", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressGreaterThanOrEqualTo(String value) {
            addCriterion("CM_SHOPEADDRESS >=", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressLessThan(String value) {
            addCriterion("CM_SHOPEADDRESS <", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressLessThanOrEqualTo(String value) {
            addCriterion("CM_SHOPEADDRESS <=", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressLike(String value) {
            addCriterion("CM_SHOPEADDRESS like", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressNotLike(String value) {
            addCriterion("CM_SHOPEADDRESS not like", value, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressIn(List<String> values) {
            addCriterion("CM_SHOPEADDRESS in", values, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressNotIn(List<String> values) {
            addCriterion("CM_SHOPEADDRESS not in", values, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressBetween(String value1, String value2) {
            addCriterion("CM_SHOPEADDRESS between", value1, value2, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShopeaddressNotBetween(String value1, String value2) {
            addCriterion("CM_SHOPEADDRESS not between", value1, value2, "cmShopeaddress");
            return (Criteria) this;
        }

        public Criteria andCmShoplonIsNull() {
            addCriterion("CM_SHOPLON is null");
            return (Criteria) this;
        }

        public Criteria andCmShoplonIsNotNull() {
            addCriterion("CM_SHOPLON is not null");
            return (Criteria) this;
        }

        public Criteria andCmShoplonEqualTo(Double value) {
            addCriterion("CM_SHOPLON =", value, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonNotEqualTo(Double value) {
            addCriterion("CM_SHOPLON <>", value, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonGreaterThan(Double value) {
            addCriterion("CM_SHOPLON >", value, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonGreaterThanOrEqualTo(Double value) {
            addCriterion("CM_SHOPLON >=", value, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonLessThan(Double value) {
            addCriterion("CM_SHOPLON <", value, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonLessThanOrEqualTo(Double value) {
            addCriterion("CM_SHOPLON <=", value, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonIn(List<Double> values) {
            addCriterion("CM_SHOPLON in", values, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonNotIn(List<Double> values) {
            addCriterion("CM_SHOPLON not in", values, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonBetween(Double value1, Double value2) {
            addCriterion("CM_SHOPLON between", value1, value2, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplonNotBetween(Double value1, Double value2) {
            addCriterion("CM_SHOPLON not between", value1, value2, "cmShoplon");
            return (Criteria) this;
        }

        public Criteria andCmShoplatIsNull() {
            addCriterion("CM_SHOPLAT is null");
            return (Criteria) this;
        }

        public Criteria andCmShoplatIsNotNull() {
            addCriterion("CM_SHOPLAT is not null");
            return (Criteria) this;
        }

        public Criteria andCmShoplatEqualTo(Double value) {
            addCriterion("CM_SHOPLAT =", value, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatNotEqualTo(Double value) {
            addCriterion("CM_SHOPLAT <>", value, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatGreaterThan(Double value) {
            addCriterion("CM_SHOPLAT >", value, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatGreaterThanOrEqualTo(Double value) {
            addCriterion("CM_SHOPLAT >=", value, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatLessThan(Double value) {
            addCriterion("CM_SHOPLAT <", value, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatLessThanOrEqualTo(Double value) {
            addCriterion("CM_SHOPLAT <=", value, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatIn(List<Double> values) {
            addCriterion("CM_SHOPLAT in", values, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatNotIn(List<Double> values) {
            addCriterion("CM_SHOPLAT not in", values, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatBetween(Double value1, Double value2) {
            addCriterion("CM_SHOPLAT between", value1, value2, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmShoplatNotBetween(Double value1, Double value2) {
            addCriterion("CM_SHOPLAT not between", value1, value2, "cmShoplat");
            return (Criteria) this;
        }

        public Criteria andCmLevelIsNull() {
            addCriterion("CM_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andCmLevelIsNotNull() {
            addCriterion("CM_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andCmLevelEqualTo(Integer value) {
            addCriterion("CM_LEVEL =", value, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelNotEqualTo(Integer value) {
            addCriterion("CM_LEVEL <>", value, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelGreaterThan(Integer value) {
            addCriterion("CM_LEVEL >", value, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("CM_LEVEL >=", value, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelLessThan(Integer value) {
            addCriterion("CM_LEVEL <", value, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelLessThanOrEqualTo(Integer value) {
            addCriterion("CM_LEVEL <=", value, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelIn(List<Integer> values) {
            addCriterion("CM_LEVEL in", values, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelNotIn(List<Integer> values) {
            addCriterion("CM_LEVEL not in", values, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelBetween(Integer value1, Integer value2) {
            addCriterion("CM_LEVEL between", value1, value2, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("CM_LEVEL not between", value1, value2, "cmLevel");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeIsNull() {
            addCriterion("CM_CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeIsNotNull() {
            addCriterion("CM_CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeEqualTo(Date value) {
            addCriterion("CM_CREATETIME =", value, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeNotEqualTo(Date value) {
            addCriterion("CM_CREATETIME <>", value, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeGreaterThan(Date value) {
            addCriterion("CM_CREATETIME >", value, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CM_CREATETIME >=", value, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeLessThan(Date value) {
            addCriterion("CM_CREATETIME <", value, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CM_CREATETIME <=", value, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeIn(List<Date> values) {
            addCriterion("CM_CREATETIME in", values, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeNotIn(List<Date> values) {
            addCriterion("CM_CREATETIME not in", values, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CM_CREATETIME between", value1, value2, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CM_CREATETIME not between", value1, value2, "cmCreatetime");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineIsNull() {
            addCriterion("CM_ISEXAMINE is null");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineIsNotNull() {
            addCriterion("CM_ISEXAMINE is not null");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineEqualTo(Integer value) {
            addCriterion("CM_ISEXAMINE =", value, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineNotEqualTo(Integer value) {
            addCriterion("CM_ISEXAMINE <>", value, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineGreaterThan(Integer value) {
            addCriterion("CM_ISEXAMINE >", value, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineGreaterThanOrEqualTo(Integer value) {
            addCriterion("CM_ISEXAMINE >=", value, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineLessThan(Integer value) {
            addCriterion("CM_ISEXAMINE <", value, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineLessThanOrEqualTo(Integer value) {
            addCriterion("CM_ISEXAMINE <=", value, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineIn(List<Integer> values) {
            addCriterion("CM_ISEXAMINE in", values, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineNotIn(List<Integer> values) {
            addCriterion("CM_ISEXAMINE not in", values, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineBetween(Integer value1, Integer value2) {
            addCriterion("CM_ISEXAMINE between", value1, value2, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmIsexamineNotBetween(Integer value1, Integer value2) {
            addCriterion("CM_ISEXAMINE not between", value1, value2, "cmIsexamine");
            return (Criteria) this;
        }

        public Criteria andCmReasonIsNull() {
            addCriterion("CM_REASON is null");
            return (Criteria) this;
        }

        public Criteria andCmReasonIsNotNull() {
            addCriterion("CM_REASON is not null");
            return (Criteria) this;
        }

        public Criteria andCmReasonEqualTo(String value) {
            addCriterion("CM_REASON =", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonNotEqualTo(String value) {
            addCriterion("CM_REASON <>", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonGreaterThan(String value) {
            addCriterion("CM_REASON >", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonGreaterThanOrEqualTo(String value) {
            addCriterion("CM_REASON >=", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonLessThan(String value) {
            addCriterion("CM_REASON <", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonLessThanOrEqualTo(String value) {
            addCriterion("CM_REASON <=", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonLike(String value) {
            addCriterion("CM_REASON like", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonNotLike(String value) {
            addCriterion("CM_REASON not like", value, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonIn(List<String> values) {
            addCriterion("CM_REASON in", values, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonNotIn(List<String> values) {
            addCriterion("CM_REASON not in", values, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonBetween(String value1, String value2) {
            addCriterion("CM_REASON between", value1, value2, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmReasonNotBetween(String value1, String value2) {
            addCriterion("CM_REASON not between", value1, value2, "cmReason");
            return (Criteria) this;
        }

        public Criteria andCmCardnoIsNull() {
            addCriterion("CM_CARDNO is null");
            return (Criteria) this;
        }

        public Criteria andCmCardnoIsNotNull() {
            addCriterion("CM_CARDNO is not null");
            return (Criteria) this;
        }

        public Criteria andCmCardnoEqualTo(String value) {
            addCriterion("CM_CARDNO =", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoNotEqualTo(String value) {
            addCriterion("CM_CARDNO <>", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoGreaterThan(String value) {
            addCriterion("CM_CARDNO >", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoGreaterThanOrEqualTo(String value) {
            addCriterion("CM_CARDNO >=", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoLessThan(String value) {
            addCriterion("CM_CARDNO <", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoLessThanOrEqualTo(String value) {
            addCriterion("CM_CARDNO <=", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoLike(String value) {
            addCriterion("CM_CARDNO like", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoNotLike(String value) {
            addCriterion("CM_CARDNO not like", value, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoIn(List<String> values) {
            addCriterion("CM_CARDNO in", values, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoNotIn(List<String> values) {
            addCriterion("CM_CARDNO not in", values, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoBetween(String value1, String value2) {
            addCriterion("CM_CARDNO between", value1, value2, "cmCardno");
            return (Criteria) this;
        }

        public Criteria andCmCardnoNotBetween(String value1, String value2) {
            addCriterion("CM_CARDNO not between", value1, value2, "cmCardno");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USERS
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 06 15:57:05 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TB_USERS
     *
     * @mbg.generated Thu Apr 06 15:57:05 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}