package com.sc.domain.generator;

public class Admins {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMINS.CM_ADMINID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmAdminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMINS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMINS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMINS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMINS.CM_LEVEL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMINS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Long cmPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMINS.CM_ADMINID
     *
     * @return the value of TB_ADMINS.CM_ADMINID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmAdminid() {
        return cmAdminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMINS.CM_ADMINID
     *
     * @param cmAdminid the value for TB_ADMINS.CM_ADMINID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmAdminid(String cmAdminid) {
        this.cmAdminid = cmAdminid == null ? null : cmAdminid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMINS.CM_NAME
     *
     * @return the value of TB_ADMINS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMINS.CM_NAME
     *
     * @param cmName the value for TB_ADMINS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMINS.CM_ACCOUNT
     *
     * @return the value of TB_ADMINS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmAccount() {
        return cmAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMINS.CM_ACCOUNT
     *
     * @param cmAccount the value for TB_ADMINS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmAccount(String cmAccount) {
        this.cmAccount = cmAccount == null ? null : cmAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMINS.CM_PASSWORD
     *
     * @return the value of TB_ADMINS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmPassword() {
        return cmPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMINS.CM_PASSWORD
     *
     * @param cmPassword the value for TB_ADMINS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPassword(String cmPassword) {
        this.cmPassword = cmPassword == null ? null : cmPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMINS.CM_LEVEL
     *
     * @return the value of TB_ADMINS.CM_LEVEL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmLevel() {
        return cmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMINS.CM_LEVEL
     *
     * @param cmLevel the value for TB_ADMINS.CM_LEVEL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmLevel(Integer cmLevel) {
        this.cmLevel = cmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMINS.CM_PHONE
     *
     * @return the value of TB_ADMINS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Long getCmPhone() {
        return cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMINS.CM_PHONE
     *
     * @param cmPhone the value for TB_ADMINS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPhone(Long cmPhone) {
        this.cmPhone = cmPhone;
    }
}