package com.sc.domain.generator;

import java.util.Date;

public class Register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REGISTER.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Long cmPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REGISTER.CM_CODE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REGISTER.CM_TIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Date cmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_REGISTER.CM_COUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REGISTER.CM_PHONE
     *
     * @return the value of TB_REGISTER.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Long getCmPhone() {
        return cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REGISTER.CM_PHONE
     *
     * @param cmPhone the value for TB_REGISTER.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPhone(Long cmPhone) {
        this.cmPhone = cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REGISTER.CM_CODE
     *
     * @return the value of TB_REGISTER.CM_CODE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmCode() {
        return cmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REGISTER.CM_CODE
     *
     * @param cmCode the value for TB_REGISTER.CM_CODE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCode(Integer cmCode) {
        this.cmCode = cmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REGISTER.CM_TIME
     *
     * @return the value of TB_REGISTER.CM_TIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Date getCmTime() {
        return cmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REGISTER.CM_TIME
     *
     * @param cmTime the value for TB_REGISTER.CM_TIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmTime(Date cmTime) {
        this.cmTime = cmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_REGISTER.CM_COUNT
     *
     * @return the value of TB_REGISTER.CM_COUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmCount() {
        return cmCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_REGISTER.CM_COUNT
     *
     * @param cmCount the value for TB_REGISTER.CM_COUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCount(Integer cmCount) {
        this.cmCount = cmCount;
    }
}