package com.sc.domain.generator;

import java.util.Date;

public class Sellers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_SELLERID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmSellerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_SELLERNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmSellername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Long cmPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_BRANDID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmBrandid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_CARDPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmCardpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_STOREPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmStorepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_LICENSEPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmLicensepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_ADDRESS
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_LON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Double cmLon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_LAT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Double cmLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_CREATETIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Date cmCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_ISEXAMINE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmIsexamine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_REASON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_CARDNO
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmCardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_CONTACTNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmContactname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_CONTACTPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmContactphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_TELEPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SELLERS.CM_PAX
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmPax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_SELLERID
     *
     * @return the value of TB_SELLERS.CM_SELLERID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmSellerid() {
        return cmSellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_SELLERID
     *
     * @param cmSellerid the value for TB_SELLERS.CM_SELLERID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmSellerid(String cmSellerid) {
        this.cmSellerid = cmSellerid == null ? null : cmSellerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_SELLERNAME
     *
     * @return the value of TB_SELLERS.CM_SELLERNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmSellername() {
        return cmSellername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_SELLERNAME
     *
     * @param cmSellername the value for TB_SELLERS.CM_SELLERNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmSellername(String cmSellername) {
        this.cmSellername = cmSellername == null ? null : cmSellername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_PHONE
     *
     * @return the value of TB_SELLERS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Long getCmPhone() {
        return cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_PHONE
     *
     * @param cmPhone the value for TB_SELLERS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPhone(Long cmPhone) {
        this.cmPhone = cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_ACCOUNT
     *
     * @return the value of TB_SELLERS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmAccount() {
        return cmAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_ACCOUNT
     *
     * @param cmAccount the value for TB_SELLERS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmAccount(String cmAccount) {
        this.cmAccount = cmAccount == null ? null : cmAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_PASSWORD
     *
     * @return the value of TB_SELLERS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmPassword() {
        return cmPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_PASSWORD
     *
     * @param cmPassword the value for TB_SELLERS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPassword(String cmPassword) {
        this.cmPassword = cmPassword == null ? null : cmPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_BRANDID
     *
     * @return the value of TB_SELLERS.CM_BRANDID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmBrandid() {
        return cmBrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_BRANDID
     *
     * @param cmBrandid the value for TB_SELLERS.CM_BRANDID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmBrandid(Integer cmBrandid) {
        this.cmBrandid = cmBrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_CARDPATH
     *
     * @return the value of TB_SELLERS.CM_CARDPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmCardpath() {
        return cmCardpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_CARDPATH
     *
     * @param cmCardpath the value for TB_SELLERS.CM_CARDPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCardpath(String cmCardpath) {
        this.cmCardpath = cmCardpath == null ? null : cmCardpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_STOREPATH
     *
     * @return the value of TB_SELLERS.CM_STOREPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmStorepath() {
        return cmStorepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_STOREPATH
     *
     * @param cmStorepath the value for TB_SELLERS.CM_STOREPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmStorepath(String cmStorepath) {
        this.cmStorepath = cmStorepath == null ? null : cmStorepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_LICENSEPATH
     *
     * @return the value of TB_SELLERS.CM_LICENSEPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmLicensepath() {
        return cmLicensepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_LICENSEPATH
     *
     * @param cmLicensepath the value for TB_SELLERS.CM_LICENSEPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmLicensepath(String cmLicensepath) {
        this.cmLicensepath = cmLicensepath == null ? null : cmLicensepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_ADDRESS
     *
     * @return the value of TB_SELLERS.CM_ADDRESS
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmAddress() {
        return cmAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_ADDRESS
     *
     * @param cmAddress the value for TB_SELLERS.CM_ADDRESS
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmAddress(String cmAddress) {
        this.cmAddress = cmAddress == null ? null : cmAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_LON
     *
     * @return the value of TB_SELLERS.CM_LON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Double getCmLon() {
        return cmLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_LON
     *
     * @param cmLon the value for TB_SELLERS.CM_LON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmLon(Double cmLon) {
        this.cmLon = cmLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_LAT
     *
     * @return the value of TB_SELLERS.CM_LAT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Double getCmLat() {
        return cmLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_LAT
     *
     * @param cmLat the value for TB_SELLERS.CM_LAT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmLat(Double cmLat) {
        this.cmLat = cmLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_CREATETIME
     *
     * @return the value of TB_SELLERS.CM_CREATETIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Date getCmCreatetime() {
        return cmCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_CREATETIME
     *
     * @param cmCreatetime the value for TB_SELLERS.CM_CREATETIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCreatetime(Date cmCreatetime) {
        this.cmCreatetime = cmCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_ISEXAMINE
     *
     * @return the value of TB_SELLERS.CM_ISEXAMINE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmIsexamine() {
        return cmIsexamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_ISEXAMINE
     *
     * @param cmIsexamine the value for TB_SELLERS.CM_ISEXAMINE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmIsexamine(Integer cmIsexamine) {
        this.cmIsexamine = cmIsexamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_REASON
     *
     * @return the value of TB_SELLERS.CM_REASON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmReason() {
        return cmReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_REASON
     *
     * @param cmReason the value for TB_SELLERS.CM_REASON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmReason(String cmReason) {
        this.cmReason = cmReason == null ? null : cmReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_CARDNO
     *
     * @return the value of TB_SELLERS.CM_CARDNO
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmCardno() {
        return cmCardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_CARDNO
     *
     * @param cmCardno the value for TB_SELLERS.CM_CARDNO
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCardno(String cmCardno) {
        this.cmCardno = cmCardno == null ? null : cmCardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_NAME
     *
     * @return the value of TB_SELLERS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_NAME
     *
     * @param cmName the value for TB_SELLERS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_CONTACTNAME
     *
     * @return the value of TB_SELLERS.CM_CONTACTNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmContactname() {
        return cmContactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_CONTACTNAME
     *
     * @param cmContactname the value for TB_SELLERS.CM_CONTACTNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmContactname(String cmContactname) {
        this.cmContactname = cmContactname == null ? null : cmContactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_CONTACTPHONE
     *
     * @return the value of TB_SELLERS.CM_CONTACTPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmContactphone() {
        return cmContactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_CONTACTPHONE
     *
     * @param cmContactphone the value for TB_SELLERS.CM_CONTACTPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmContactphone(String cmContactphone) {
        this.cmContactphone = cmContactphone == null ? null : cmContactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_TELEPHONE
     *
     * @return the value of TB_SELLERS.CM_TELEPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmTelephone() {
        return cmTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_TELEPHONE
     *
     * @param cmTelephone the value for TB_SELLERS.CM_TELEPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmTelephone(String cmTelephone) {
        this.cmTelephone = cmTelephone == null ? null : cmTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SELLERS.CM_PAX
     *
     * @return the value of TB_SELLERS.CM_PAX
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmPax() {
        return cmPax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SELLERS.CM_PAX
     *
     * @param cmPax the value for TB_SELLERS.CM_PAX
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPax(String cmPax) {
        this.cmPax = cmPax == null ? null : cmPax.trim();
    }
}