package com.sc.domain.generator;

import java.util.Date;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_USERID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_SHOPNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmShopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Long cmPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_INTEGRAL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_BALANCE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Double cmBalance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_CARDPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmCardpath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_STOREPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmStorepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_LICENSEPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmLicensepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_SHOPEADDRESS
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmShopeaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_SHOPLON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Double cmShoplon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_SHOPLAT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Double cmShoplat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_LEVEL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_CREATETIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Date cmCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_ISEXAMINE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private Integer cmIsexamine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_REASON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_CARDNO
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmCardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_CONTACTNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmContactname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_CONTACTPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmContactphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_TELEPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_USERS.CM_PAX
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    private String cmPax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_USERID
     *
     * @return the value of TB_USERS.CM_USERID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmUserid() {
        return cmUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_USERID
     *
     * @param cmUserid the value for TB_USERS.CM_USERID
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmUserid(String cmUserid) {
        this.cmUserid = cmUserid == null ? null : cmUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_SHOPNAME
     *
     * @return the value of TB_USERS.CM_SHOPNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmShopname() {
        return cmShopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_SHOPNAME
     *
     * @param cmShopname the value for TB_USERS.CM_SHOPNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmShopname(String cmShopname) {
        this.cmShopname = cmShopname == null ? null : cmShopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_PHONE
     *
     * @return the value of TB_USERS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Long getCmPhone() {
        return cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_PHONE
     *
     * @param cmPhone the value for TB_USERS.CM_PHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPhone(Long cmPhone) {
        this.cmPhone = cmPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_ACCOUNT
     *
     * @return the value of TB_USERS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmAccount() {
        return cmAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_ACCOUNT
     *
     * @param cmAccount the value for TB_USERS.CM_ACCOUNT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmAccount(String cmAccount) {
        this.cmAccount = cmAccount == null ? null : cmAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_PASSWORD
     *
     * @return the value of TB_USERS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmPassword() {
        return cmPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_PASSWORD
     *
     * @param cmPassword the value for TB_USERS.CM_PASSWORD
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPassword(String cmPassword) {
        this.cmPassword = cmPassword == null ? null : cmPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_INTEGRAL
     *
     * @return the value of TB_USERS.CM_INTEGRAL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmIntegral() {
        return cmIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_INTEGRAL
     *
     * @param cmIntegral the value for TB_USERS.CM_INTEGRAL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmIntegral(Integer cmIntegral) {
        this.cmIntegral = cmIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_BALANCE
     *
     * @return the value of TB_USERS.CM_BALANCE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Double getCmBalance() {
        return cmBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_BALANCE
     *
     * @param cmBalance the value for TB_USERS.CM_BALANCE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmBalance(Double cmBalance) {
        this.cmBalance = cmBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_CARDPATH
     *
     * @return the value of TB_USERS.CM_CARDPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmCardpath() {
        return cmCardpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_CARDPATH
     *
     * @param cmCardpath the value for TB_USERS.CM_CARDPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCardpath(String cmCardpath) {
        this.cmCardpath = cmCardpath == null ? null : cmCardpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_STOREPATH
     *
     * @return the value of TB_USERS.CM_STOREPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmStorepath() {
        return cmStorepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_STOREPATH
     *
     * @param cmStorepath the value for TB_USERS.CM_STOREPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmStorepath(String cmStorepath) {
        this.cmStorepath = cmStorepath == null ? null : cmStorepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_LICENSEPATH
     *
     * @return the value of TB_USERS.CM_LICENSEPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmLicensepath() {
        return cmLicensepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_LICENSEPATH
     *
     * @param cmLicensepath the value for TB_USERS.CM_LICENSEPATH
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmLicensepath(String cmLicensepath) {
        this.cmLicensepath = cmLicensepath == null ? null : cmLicensepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_SHOPEADDRESS
     *
     * @return the value of TB_USERS.CM_SHOPEADDRESS
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmShopeaddress() {
        return cmShopeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_SHOPEADDRESS
     *
     * @param cmShopeaddress the value for TB_USERS.CM_SHOPEADDRESS
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmShopeaddress(String cmShopeaddress) {
        this.cmShopeaddress = cmShopeaddress == null ? null : cmShopeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_SHOPLON
     *
     * @return the value of TB_USERS.CM_SHOPLON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Double getCmShoplon() {
        return cmShoplon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_SHOPLON
     *
     * @param cmShoplon the value for TB_USERS.CM_SHOPLON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmShoplon(Double cmShoplon) {
        this.cmShoplon = cmShoplon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_SHOPLAT
     *
     * @return the value of TB_USERS.CM_SHOPLAT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Double getCmShoplat() {
        return cmShoplat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_SHOPLAT
     *
     * @param cmShoplat the value for TB_USERS.CM_SHOPLAT
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmShoplat(Double cmShoplat) {
        this.cmShoplat = cmShoplat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_LEVEL
     *
     * @return the value of TB_USERS.CM_LEVEL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmLevel() {
        return cmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_LEVEL
     *
     * @param cmLevel the value for TB_USERS.CM_LEVEL
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmLevel(Integer cmLevel) {
        this.cmLevel = cmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_CREATETIME
     *
     * @return the value of TB_USERS.CM_CREATETIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Date getCmCreatetime() {
        return cmCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_CREATETIME
     *
     * @param cmCreatetime the value for TB_USERS.CM_CREATETIME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCreatetime(Date cmCreatetime) {
        this.cmCreatetime = cmCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_ISEXAMINE
     *
     * @return the value of TB_USERS.CM_ISEXAMINE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public Integer getCmIsexamine() {
        return cmIsexamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_ISEXAMINE
     *
     * @param cmIsexamine the value for TB_USERS.CM_ISEXAMINE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmIsexamine(Integer cmIsexamine) {
        this.cmIsexamine = cmIsexamine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_REASON
     *
     * @return the value of TB_USERS.CM_REASON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmReason() {
        return cmReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_REASON
     *
     * @param cmReason the value for TB_USERS.CM_REASON
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmReason(String cmReason) {
        this.cmReason = cmReason == null ? null : cmReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_CARDNO
     *
     * @return the value of TB_USERS.CM_CARDNO
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmCardno() {
        return cmCardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_CARDNO
     *
     * @param cmCardno the value for TB_USERS.CM_CARDNO
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmCardno(String cmCardno) {
        this.cmCardno = cmCardno == null ? null : cmCardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_NAME
     *
     * @return the value of TB_USERS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmName() {
        return cmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_NAME
     *
     * @param cmName the value for TB_USERS.CM_NAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmName(String cmName) {
        this.cmName = cmName == null ? null : cmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_CONTACTNAME
     *
     * @return the value of TB_USERS.CM_CONTACTNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmContactname() {
        return cmContactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_CONTACTNAME
     *
     * @param cmContactname the value for TB_USERS.CM_CONTACTNAME
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmContactname(String cmContactname) {
        this.cmContactname = cmContactname == null ? null : cmContactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_CONTACTPHONE
     *
     * @return the value of TB_USERS.CM_CONTACTPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmContactphone() {
        return cmContactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_CONTACTPHONE
     *
     * @param cmContactphone the value for TB_USERS.CM_CONTACTPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmContactphone(String cmContactphone) {
        this.cmContactphone = cmContactphone == null ? null : cmContactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_TELEPHONE
     *
     * @return the value of TB_USERS.CM_TELEPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmTelephone() {
        return cmTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_TELEPHONE
     *
     * @param cmTelephone the value for TB_USERS.CM_TELEPHONE
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmTelephone(String cmTelephone) {
        this.cmTelephone = cmTelephone == null ? null : cmTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_USERS.CM_PAX
     *
     * @return the value of TB_USERS.CM_PAX
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public String getCmPax() {
        return cmPax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_USERS.CM_PAX
     *
     * @param cmPax the value for TB_USERS.CM_PAX
     *
     * @mbg.generated Wed Apr 26 09:05:28 CST 2017
     */
    public void setCmPax(String cmPax) {
        this.cmPax = cmPax == null ? null : cmPax.trim();
    }
}