package com.sc.mapper.generator;

import com.sc.domain.generator.RadCode;
import com.sc.domain.generator.RadCodeExample;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface RadCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @SelectProvider(type=RadCodeSqlProvider.class, method="countByExample")
    long countByExample(RadCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @DeleteProvider(type=RadCodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(RadCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @Insert({
        "insert into TB_RADCODE (CM_USERID, CM_CODE)",
        "values (#{cmUserid,jdbcType=VARCHAR}, #{cmCode,jdbcType=INTEGER})"
    })
    int insert(RadCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @InsertProvider(type=RadCodeSqlProvider.class, method="insertSelective")
    int insertSelective(RadCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @SelectProvider(type=RadCodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="CM_USERID", property="cmUserid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_CODE", property="cmCode", jdbcType=JdbcType.INTEGER)
    })
    List<RadCode> selectByExample(RadCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @UpdateProvider(type=RadCodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RadCode record, @Param("example") RadCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_RADCODE
     *
     * @mbg.generated Fri Apr 14 11:43:54 CST 2017
     */
    @UpdateProvider(type=RadCodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RadCode record, @Param("example") RadCodeExample example);
}