package com.sc.mapper.generator;

import com.sc.domain.generator.Sellers;
import com.sc.domain.generator.SellersExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SellersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @SelectProvider(type=SellersSqlProvider.class, method="countByExample")
    long countByExample(SellersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @DeleteProvider(type=SellersSqlProvider.class, method="deleteByExample")
    int deleteByExample(SellersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @Insert({
        "insert into TB_SELLERS (CM_SELLERID, CM_SELLERNAME, ",
        "CM_PHONE, CM_ACCOUNT, ",
        "CM_PASSWORD, CM_BRANDID, ",
        "CM_CARDFACEPATH, CM_CARDBACKPATH, ",
        "CM_PERSONALPATH, CM_LICENSEPATH, ",
        "CM_ADDRESS, CM_LON, ",
        "CM_LAT, CM_CREATETIME, ",
        "CM_ISEXAMINE, CM_REASON, ",
        "CM_CARDNO)",
        "values (#{cmSellerid,jdbcType=VARCHAR}, #{cmSellername,jdbcType=VARCHAR}, ",
        "#{cmPhone,jdbcType=BIGINT}, #{cmAccount,jdbcType=VARCHAR}, ",
        "#{cmPassword,jdbcType=VARCHAR}, #{cmBrandid,jdbcType=INTEGER}, ",
        "#{cmCardfacepath,jdbcType=VARCHAR}, #{cmCardbackpath,jdbcType=VARCHAR}, ",
        "#{cmPersonalpath,jdbcType=VARCHAR}, #{cmLicensepath,jdbcType=VARCHAR}, ",
        "#{cmAddress,jdbcType=VARCHAR}, #{cmLon,jdbcType=DOUBLE}, ",
        "#{cmLat,jdbcType=DOUBLE}, #{cmCreatetime,jdbcType=TIMESTAMP}, ",
        "#{cmIsexamine,jdbcType=INTEGER}, #{cmReason,jdbcType=VARCHAR}, ",
        "#{cmCardno,jdbcType=VARCHAR})"
    })
    int insert(Sellers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @InsertProvider(type=SellersSqlProvider.class, method="insertSelective")
    int insertSelective(Sellers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @SelectProvider(type=SellersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="CM_SELLERID", property="cmSellerid", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_SELLERNAME", property="cmSellername", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_PHONE", property="cmPhone", jdbcType=JdbcType.BIGINT),
        @Result(column="CM_ACCOUNT", property="cmAccount", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_PASSWORD", property="cmPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_BRANDID", property="cmBrandid", jdbcType=JdbcType.INTEGER),
        @Result(column="CM_CARDFACEPATH", property="cmCardfacepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_CARDBACKPATH", property="cmCardbackpath", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_PERSONALPATH", property="cmPersonalpath", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_LICENSEPATH", property="cmLicensepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_ADDRESS", property="cmAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_LON", property="cmLon", jdbcType=JdbcType.DOUBLE),
        @Result(column="CM_LAT", property="cmLat", jdbcType=JdbcType.DOUBLE),
        @Result(column="CM_CREATETIME", property="cmCreatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CM_ISEXAMINE", property="cmIsexamine", jdbcType=JdbcType.INTEGER),
        @Result(column="CM_REASON", property="cmReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="CM_CARDNO", property="cmCardno", jdbcType=JdbcType.VARCHAR)
    })
    List<Sellers> selectByExample(SellersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @UpdateProvider(type=SellersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Sellers record, @Param("example") SellersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SELLERS
     *
     * @mbg.generated Tue Apr 18 16:01:00 CST 2017
     */
    @UpdateProvider(type=SellersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Sellers record, @Param("example") SellersExample example);
}